# Generated by Django 4.0.4 on 2022-06-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mprs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('owner_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('upvote', models.PositiveIntegerField(default=0)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', mprs.models.NameField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='mprs.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mprs.commentmodel')),
                ('owner_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='mprs.tagmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mprs.projectmodel'),
        ),
    ]
