# Generated by Django 4.0.5 on 2022-06-07 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mprs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='url',
            field=models.URLField(default='https://jsonplaceholder.typicode.com/'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='voteCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='votedBy',
            field=models.ManyToManyField(related_name='project_voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='tag',
            field=models.ManyToManyField(related_name='projects', to='mprs.tagmodel'),
        ),
    ]
