# Generated by Django 4.0.5 on 2022-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprs', '0003_commentmodel_last_edit_projectmodel_last_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='last_edit',
        ),
        migrations.RemoveField(
            model_name='replymodel',
            name='last_edit',
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
