# Generated by Django 4.0.5 on 2022-06-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprs', '0005_rename_date_commentmodel_last_modify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='upvote',
        ),
    ]
