# Generated by Django 4.0.5 on 2022-06-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprs', '0006_remove_projectmodel_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='voteCount',
        ),
    ]
